# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Asparator(object):
    def setupUi(self, Asparator):
        Asparator.setObjectName("Asparator")
        Asparator.resize(673, 599)
        self.centralwidget = QtWidgets.QWidget(Asparator)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = ImageDisplay(self.widget_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.previous_asparagus = QtWidgets.QPushButton(self.widget)
        self.previous_asparagus.setObjectName("previous_asparagus")
        self.horizontalLayout_2.addWidget(self.previous_asparagus)
        self.next_asparagus = QtWidgets.QPushButton(self.widget)
        self.next_asparagus.setObjectName("next_asparagus")
        self.horizontalLayout_2.addWidget(self.next_asparagus)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.start_labeling = QtWidgets.QPushButton(self.widget)
        self.start_labeling.setObjectName("start_labeling")
        self.horizontalLayout_2.addWidget(self.start_labeling)
        self.verticalLayout.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(self.splitter)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table = QtWidgets.QTableView(self.widget_4)
        self.table.setObjectName("table")
        self.verticalLayout_3.addWidget(self.table)
        self.horizontalLayout.addWidget(self.splitter)
        Asparator.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Asparator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 673, 17))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        Asparator.setMenuBar(self.menuBar)
        self.actionOpen_folder = QtWidgets.QAction(Asparator)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionClose = QtWidgets.QAction(Asparator)
        self.actionClose.setObjectName("actionClose")
        self.actionClose_2 = QtWidgets.QAction(Asparator)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionHo = QtWidgets.QAction(Asparator)
        self.actionHo.setObjectName("actionHo")
        self.actionHa = QtWidgets.QAction(Asparator)
        self.actionHa.setObjectName("actionHa")
        self.actionOpen_file_directory = QtWidgets.QAction(Asparator)
        self.actionOpen_file_directory.setObjectName("actionOpen_file_directory")
        self.actionOpen_labeling_dialog = QtWidgets.QAction(Asparator)
        self.actionOpen_labeling_dialog.setObjectName("actionOpen_labeling_dialog")
        self.actionClose_3 = QtWidgets.QAction(Asparator)
        self.actionClose_3.setObjectName("actionClose_3")
        self.actionLoad_label_file = QtWidgets.QAction(Asparator)
        self.actionLoad_label_file.setObjectName("actionLoad_label_file")
        self.actionCreate_new_label_file = QtWidgets.QAction(Asparator)
        self.actionCreate_new_label_file.setObjectName("actionCreate_new_label_file")
        self.actionHelp = QtWidgets.QAction(Asparator)
        self.actionHelp.setObjectName("actionHelp")
        self.menuFile.addAction(self.actionOpen_file_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCreate_new_label_file)
        self.menuFile.addAction(self.actionLoad_label_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_labeling_dialog)
        self.menuFile.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionClose_3)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Asparator)
        QtCore.QMetaObject.connectSlotsByName(Asparator)

    def retranslateUi(self, Asparator):
        _translate = QtCore.QCoreApplication.translate
        Asparator.setWindowTitle(_translate("Asparator", "Asparator"))
        self.previous_asparagus.setText(_translate("Asparator", "<<"))
        self.next_asparagus.setText(_translate("Asparator", ">>"))
        self.start_labeling.setText(_translate("Asparator", "start labeling"))
        self.menuFile.setTitle(_translate("Asparator", "File"))
        self.actionOpen_folder.setText(_translate("Asparator", "Open image folder..."))
        self.actionClose.setText(_translate("Asparator", "Open label dialog ..."))
        self.actionClose_2.setText(_translate("Asparator", "Close"))
        self.actionHo.setText(_translate("Asparator", "Open file directory ..."))
        self.actionHa.setText(_translate("Asparator", "Ha"))
        self.actionOpen_file_directory.setText(_translate("Asparator", "Open file directory ..."))
        self.actionOpen_labeling_dialog.setText(_translate("Asparator", "Open labeling dialog"))
        self.actionClose_3.setText(_translate("Asparator", "Close"))
        self.actionLoad_label_file.setText(_translate("Asparator", "Load label file"))
        self.actionCreate_new_label_file.setText(_translate("Asparator", "Create new label file"))
        self.actionHelp.setText(_translate("Asparator", "Help"))

from imagedisplay import ImageDisplay
