# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Asparator(object):
    def setupUi(self, Asparator):
        Asparator.setObjectName("Asparator")
        Asparator.resize(963, 939)
        self.centralwidget = QtWidgets.QWidget(Asparator)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.widget_3)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = ImageDisplay(self.widget)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tree = ImageDisplay(self.widget)
        self.tree.setMinimumSize(QtCore.QSize(50, 0))
        self.tree.setText("")
        self.tree.setObjectName("tree")
        self.verticalLayout_3.addWidget(self.tree)
        self.widget_2 = QtWidgets.QWidget(self.splitter)
        self.widget_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.is_bruch = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.is_bruch.sizePolicy().hasHeightForWidth())
        self.is_bruch.setSizePolicy(sizePolicy)
        self.is_bruch.setFlat(False)
        self.is_bruch.setCheckable(True)
        self.is_bruch.setChecked(False)
        self.is_bruch.setObjectName("is_bruch")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.is_bruch)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.is_bruch)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.is_bruch)
        self.is_not_bruch = QtWidgets.QGroupBox(self.widget_2)
        self.is_not_bruch.setFlat(False)
        self.is_not_bruch.setCheckable(True)
        self.is_not_bruch.setChecked(False)
        self.is_not_bruch.setObjectName("is_not_bruch")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.is_not_bruch)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.has_blume = QtWidgets.QGroupBox(self.is_not_bruch)
        self.has_blume.setCheckable(True)
        self.has_blume.setChecked(False)
        self.has_blume.setObjectName("has_blume")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.has_blume)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.is_blume_dick = QtWidgets.QGroupBox(self.has_blume)
        self.is_blume_dick.setMinimumSize(QtCore.QSize(0, 50))
        self.is_blume_dick.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_blume_dick.setCheckable(True)
        self.is_blume_dick.setChecked(False)
        self.is_blume_dick.setObjectName("is_blume_dick")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.is_blume_dick)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.is_blume_dick)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.horizontalLayout.addWidget(self.is_blume_dick)
        self.is_blume_duenn = QtWidgets.QGroupBox(self.has_blume)
        self.is_blume_duenn.setMinimumSize(QtCore.QSize(0, 50))
        self.is_blume_duenn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_blume_duenn.setCheckable(True)
        self.is_blume_duenn.setChecked(False)
        self.is_blume_duenn.setObjectName("is_blume_duenn")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.is_blume_duenn)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.is_blume_duenn)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.horizontalLayout.addWidget(self.is_blume_duenn)
        self.verticalLayout_7.addWidget(self.has_blume)
        self.has_no_blume = QtWidgets.QGroupBox(self.is_not_bruch)
        self.has_no_blume.setCheckable(True)
        self.has_no_blume.setChecked(False)
        self.has_no_blume.setObjectName("has_no_blume")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.has_no_blume)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.has_rost = QtWidgets.QGroupBox(self.has_no_blume)
        self.has_rost.setCheckable(True)
        self.has_rost.setChecked(False)
        self.has_rost.setObjectName("has_rost")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.has_rost)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.is_rost_dick = QtWidgets.QGroupBox(self.has_rost)
        self.is_rost_dick.setCheckable(True)
        self.is_rost_dick.setChecked(False)
        self.is_rost_dick.setObjectName("is_rost_dick")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.is_rost_dick)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.is_rost_dick)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.is_rost_dick)
        self.is_rost_duenn = QtWidgets.QGroupBox(self.has_rost)
        self.is_rost_duenn.setFlat(False)
        self.is_rost_duenn.setCheckable(True)
        self.is_rost_duenn.setChecked(False)
        self.is_rost_duenn.setObjectName("is_rost_duenn")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.is_rost_duenn)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.is_rost_duenn)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.horizontalLayout_3.addWidget(self.is_rost_duenn)
        self.verticalLayout_26.addWidget(self.has_rost)
        self.has_no_rost = QtWidgets.QGroupBox(self.has_no_blume)
        self.has_no_rost.setCheckable(True)
        self.has_no_rost.setChecked(False)
        self.has_no_rost.setObjectName("has_no_rost")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.has_no_rost)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.is_bended = QtWidgets.QGroupBox(self.has_no_rost)
        self.is_bended.setCheckable(True)
        self.is_bended.setChecked(False)
        self.is_bended.setObjectName("is_bended")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.is_bended)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.is_krumm_dick = QtWidgets.QGroupBox(self.is_bended)
        self.is_krumm_dick.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_krumm_dick.setCheckable(True)
        self.is_krumm_dick.setChecked(False)
        self.is_krumm_dick.setObjectName("is_krumm_dick")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.is_krumm_dick)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.is_krumm_dick)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_20.addWidget(self.label_16)
        self.verticalLayout_23.addWidget(self.is_krumm_dick)
        self.is_bended_medium = QtWidgets.QGroupBox(self.is_bended)
        self.is_bended_medium.setCheckable(True)
        self.is_bended_medium.setChecked(False)
        self.is_bended_medium.setObjectName("is_bended_medium")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.is_bended_medium)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.is_bended_medium_non_violet = QtWidgets.QGroupBox(self.is_bended_medium)
        self.is_bended_medium_non_violet.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_bended_medium_non_violet.setCheckable(True)
        self.is_bended_medium_non_violet.setChecked(False)
        self.is_bended_medium_non_violet.setObjectName("is_bended_medium_non_violet")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.is_bended_medium_non_violet)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_18 = QtWidgets.QLabel(self.is_bended_medium_non_violet)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_22.addWidget(self.label_18)
        self.verticalLayout_24.addWidget(self.is_bended_medium_non_violet)
        self.is_bended_medium_violet = QtWidgets.QGroupBox(self.is_bended_medium)
        self.is_bended_medium_violet.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_bended_medium_violet.setCheckable(True)
        self.is_bended_medium_violet.setChecked(False)
        self.is_bended_medium_violet.setObjectName("is_bended_medium_violet")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.is_bended_medium_violet)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_17 = QtWidgets.QLabel(self.is_bended_medium_violet)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_21.addWidget(self.label_17)
        self.verticalLayout_24.addWidget(self.is_bended_medium_violet)
        self.verticalLayout_23.addWidget(self.is_bended_medium)
        self.horizontalLayout_4.addWidget(self.is_bended)
        self.is_not_bended = QtWidgets.QGroupBox(self.has_no_rost)
        self.is_not_bended.setCheckable(True)
        self.is_not_bended.setChecked(False)
        self.is_not_bended.setObjectName("is_not_bended")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.is_not_bended)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.is_not_bended_non_violet = QtWidgets.QGroupBox(self.is_not_bended)
        self.is_not_bended_non_violet.setCheckable(True)
        self.is_not_bended_non_violet.setChecked(False)
        self.is_not_bended_non_violet.setObjectName("is_not_bended_non_violet")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.is_not_bended_non_violet)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.is_dicke = QtWidgets.QGroupBox(self.is_not_bended_non_violet)
        self.is_dicke.setMinimumSize(QtCore.QSize(0, 50))
        self.is_dicke.setCheckable(True)
        self.is_dicke.setChecked(False)
        self.is_dicke.setObjectName("is_dicke")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.is_dicke)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.is_dicke)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_12.addWidget(self.label_9)
        self.verticalLayout_17.addWidget(self.is_dicke)
        self.is_anna = QtWidgets.QGroupBox(self.is_not_bended_non_violet)
        self.is_anna.setMinimumSize(QtCore.QSize(0, 50))
        self.is_anna.setCheckable(True)
        self.is_anna.setChecked(False)
        self.is_anna.setObjectName("is_anna")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.is_anna)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.is_anna)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_13.addWidget(self.label_10)
        self.verticalLayout_17.addWidget(self.is_anna)
        self.is_bona = QtWidgets.QGroupBox(self.is_not_bended_non_violet)
        self.is_bona.setMinimumSize(QtCore.QSize(0, 50))
        self.is_bona.setCheckable(True)
        self.is_bona.setChecked(False)
        self.is_bona.setObjectName("is_bona")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.is_bona)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.is_bona)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.verticalLayout_17.addWidget(self.is_bona)
        self.is_clara = QtWidgets.QGroupBox(self.is_not_bended_non_violet)
        self.is_clara.setMinimumSize(QtCore.QSize(0, 50))
        self.is_clara.setCheckable(True)
        self.is_clara.setChecked(False)
        self.is_clara.setObjectName("is_clara")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.is_clara)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_12 = QtWidgets.QLabel(self.is_clara)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_15.addWidget(self.label_12)
        self.verticalLayout_17.addWidget(self.is_clara)
        self.is_suppe = QtWidgets.QGroupBox(self.is_not_bended_non_violet)
        self.is_suppe.setMinimumSize(QtCore.QSize(0, 50))
        self.is_suppe.setCheckable(True)
        self.is_suppe.setChecked(False)
        self.is_suppe.setObjectName("is_suppe")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.is_suppe)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.is_suppe)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_16.addWidget(self.label_13)
        self.verticalLayout_17.addWidget(self.is_suppe)
        self.verticalLayout_29.addWidget(self.is_not_bended_non_violet)
        self.is_not_bended_violet = QtWidgets.QGroupBox(self.is_not_bended)
        self.is_not_bended_violet.setCheckable(True)
        self.is_not_bended_violet.setChecked(False)
        self.is_not_bended_violet.setObjectName("is_not_bended_violet")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.is_not_bended_violet)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.is_violet_duenn = QtWidgets.QGroupBox(self.is_not_bended_violet)
        self.is_violet_duenn.setMinimumSize(QtCore.QSize(0, 50))
        self.is_violet_duenn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_violet_duenn.setCheckable(True)
        self.is_violet_duenn.setChecked(False)
        self.is_violet_duenn.setObjectName("is_violet_duenn")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.is_violet_duenn)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.is_violet_duenn)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.horizontalLayout_5.addWidget(self.is_violet_duenn)
        self.is_violet_dick = QtWidgets.QGroupBox(self.is_not_bended_violet)
        self.is_violet_dick.setMinimumSize(QtCore.QSize(0, 50))
        self.is_violet_dick.setMaximumSize(QtCore.QSize(16777215, 50))
        self.is_violet_dick.setCheckable(True)
        self.is_violet_dick.setChecked(False)
        self.is_violet_dick.setObjectName("is_violet_dick")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.is_violet_dick)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.is_violet_dick)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_18.addWidget(self.label_14)
        self.horizontalLayout_5.addWidget(self.is_violet_dick)
        self.verticalLayout_29.addWidget(self.is_not_bended_violet)
        self.horizontalLayout_4.addWidget(self.is_not_bended)
        self.verticalLayout_26.addWidget(self.has_no_rost)
        self.verticalLayout_7.addWidget(self.has_no_blume)
        self.verticalLayout_4.addWidget(self.is_not_bruch)
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.previous_asparagus = QtWidgets.QPushButton(self.widget1)
        self.previous_asparagus.setObjectName("previous_asparagus")
        self.horizontalLayout_2.addWidget(self.previous_asparagus)
        self.next_asparagus = QtWidgets.QPushButton(self.widget1)
        self.next_asparagus.setObjectName("next_asparagus")
        self.horizontalLayout_2.addWidget(self.next_asparagus)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.widget1)
        Asparator.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Asparator)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 963, 17))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        Asparator.setMenuBar(self.menuBar)
        self.actionOpen_folder = QtWidgets.QAction(Asparator)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionClose = QtWidgets.QAction(Asparator)
        self.actionClose.setObjectName("actionClose")
        self.actionClose_2 = QtWidgets.QAction(Asparator)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionHo = QtWidgets.QAction(Asparator)
        self.actionHo.setObjectName("actionHo")
        self.actionHa = QtWidgets.QAction(Asparator)
        self.actionHa.setObjectName("actionHa")
        self.actionOpen_file_directory = QtWidgets.QAction(Asparator)
        self.actionOpen_file_directory.setObjectName("actionOpen_file_directory")
        self.actionOpen_labeling_dialog = QtWidgets.QAction(Asparator)
        self.actionOpen_labeling_dialog.setObjectName("actionOpen_labeling_dialog")
        self.actionClose_3 = QtWidgets.QAction(Asparator)
        self.actionClose_3.setObjectName("actionClose_3")
        self.actionLoad_label_file = QtWidgets.QAction(Asparator)
        self.actionLoad_label_file.setObjectName("actionLoad_label_file")
        self.actionCreate_new_label_file = QtWidgets.QAction(Asparator)
        self.actionCreate_new_label_file.setObjectName("actionCreate_new_label_file")
        self.menuFile.addAction(self.actionOpen_file_directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCreate_new_label_file)
        self.menuFile.addAction(self.actionLoad_label_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_labeling_dialog)
        self.menuFile.addAction(self.actionClose_3)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Asparator)
        QtCore.QMetaObject.connectSlotsByName(Asparator)

    def retranslateUi(self, Asparator):
        _translate = QtCore.QCoreApplication.translate
        Asparator.setWindowTitle(_translate("Asparator", "Asparator"))
        self.is_bruch.setTitle(_translate("Asparator", "length < 21 cm"))
        self.label_4.setText(_translate("Asparator", "class: Bruch/Kerze/Köpfchen"))
        self.is_not_bruch.setTitle(_translate("Asparator", "length > 21 cm"))
        self.has_blume.setTitle(_translate("Asparator", "Blume"))
        self.is_blume_dick.setTitle(_translate("Asparator", "Width > 20 mm"))
        self.label_5.setText(_translate("Asparator", "Class: Blume dick"))
        self.is_blume_duenn.setTitle(_translate("Asparator", "Width < 20 mm"))
        self.label_6.setText(_translate("Asparator", "Class: Blume dünn"))
        self.has_no_blume.setTitle(_translate("Asparator", "No Blume"))
        self.has_rost.setTitle(_translate("Asparator", "Rost"))
        self.is_rost_dick.setTitle(_translate("Asparator", "Width > 20 mm"))
        self.label_7.setText(_translate("Asparator", "Class: Blume dick"))
        self.is_rost_duenn.setTitle(_translate("Asparator", "Width < 20 mm"))
        self.label_8.setText(_translate("Asparator", "Class: Rost dünn"))
        self.has_no_rost.setTitle(_translate("Asparator", "No Rost"))
        self.is_bended.setTitle(_translate("Asparator", "Bended"))
        self.is_krumm_dick.setTitle(_translate("Asparator", "Width > 26 mm"))
        self.label_16.setText(_translate("Asparator", "Class: Krumm Dick"))
        self.is_bended_medium.setTitle(_translate("Asparator", "Width < 20 mm"))
        self.is_bended_medium_non_violet.setTitle(_translate("Asparator", "Not violet"))
        self.label_18.setText(_translate("Asparator", "Class: Krumm Dünn"))
        self.is_bended_medium_violet.setTitle(_translate("Asparator", "Violet"))
        self.label_17.setText(_translate("Asparator", "Class: Violet Krumm"))
        self.is_not_bended.setTitle(_translate("Asparator", "Not bended"))
        self.is_not_bended_non_violet.setTitle(_translate("Asparator", "Not Violet"))
        self.is_dicke.setTitle(_translate("Asparator", "Width > 26 mm"))
        self.label_9.setText(_translate("Asparator", "Class: Dicke"))
        self.is_anna.setTitle(_translate("Asparator", "Width > 20-26 mm"))
        self.label_10.setText(_translate("Asparator", "Class: 1A Anna"))
        self.is_bona.setTitle(_translate("Asparator", "Width > 18 - 20 mm"))
        self.label_11.setText(_translate("Asparator", "Class: 1A Bona"))
        self.is_clara.setTitle(_translate("Asparator", "Width > 16-18 mm"))
        self.label_12.setText(_translate("Asparator", "Class: 1A Clara"))
        self.is_suppe.setTitle(_translate("Asparator", "Width < 16"))
        self.label_13.setText(_translate("Asparator", "Class: Suppe"))
        self.is_not_bended_violet.setTitle(_translate("Asparator", "Violet"))
        self.is_violet_duenn.setTitle(_translate("Asparator", "Width > 26 mm"))
        self.label_15.setText(_translate("Asparator", "Class: Violet Dünn"))
        self.is_violet_dick.setTitle(_translate("Asparator", "Width > 26 mm"))
        self.label_14.setText(_translate("Asparator", "Class: Violet Dick"))
        self.previous_asparagus.setText(_translate("Asparator", "<<"))
        self.next_asparagus.setText(_translate("Asparator", ">>"))
        self.label_2.setText(_translate("Asparator", "Aspargus no. 1a"))
        self.menuFile.setTitle(_translate("Asparator", "File"))
        self.actionOpen_folder.setText(_translate("Asparator", "Open image folder..."))
        self.actionClose.setText(_translate("Asparator", "Open label dialog ..."))
        self.actionClose_2.setText(_translate("Asparator", "Close"))
        self.actionHo.setText(_translate("Asparator", "Open file directory ..."))
        self.actionHa.setText(_translate("Asparator", "Ha"))
        self.actionOpen_file_directory.setText(_translate("Asparator", "Open file directory ..."))
        self.actionOpen_labeling_dialog.setText(_translate("Asparator", "Open labeling dialog"))
        self.actionClose_3.setText(_translate("Asparator", "Close"))
        self.actionLoad_label_file.setText(_translate("Asparator", "Load label file"))
        self.actionCreate_new_label_file.setText(_translate("Asparator", "Create new label file"))

from imagedisplay import ImageDisplay
